// (22/10/2019) 
// Attempts to generate all elements of the group mod 3 using two specified elements
#ifndef _BITS
#define _BITS
#include <bits/stdc++.h>
#endif
#ifndef _MATRIX
#define _MATRIX
#include "matrix.h"
#endif

// Generate all elts mod3 generated by A,B and returns them in quotient_elements
// Checks if expected size is met
vector<Matrix>& two_gen(Matrix A, Matrix B, vector<Matrix> &quotient_elements, int expected_size);
